### ISSUE TITLE
Add Biography for Shaunice

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#31]
@mnrangers

**Comment by MNRangers** [comment]
Shaunice "Niecy" Fentress
Assistant Coach

Shaunice Fentress is a native of Gary, IN and brings a different but very valued perspective being a young (22) lady. Basketball has been a big part of Shaunice's life since the age of 6, playing up until her freshman year in college. Still a student herself, Shaunice's goals as assistant coach is to assist head coach Sandifer as well as bring a fresh, young perspective to the team.
